import type { Metadata } from "next";
import { Noto_Sans_Devanagari } from 'next/font/google';
import "./globals.css";

const notoSansDevanagari = Noto_Sans_Devanagari({
  subsets: ['devanagari'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSansDevanagari.className}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
