export const lyricTimings = [
  { startTime: 0, endTime: 5.4, text: "अरे कृष्णा ! अरे कान्हा ! मनरंजनमोहना" },
  {
    startTime: 9.0,
    endTime: 14.0,
    text: "अरे कृष्णा ! अरे कान्हा ! मनरंजनमोहना",
  },
  {
    startTime: 22.0,
    endTime: 26.3,
    text: "आले संत घरीं तरी काय बोलुन शिणवावें?",
  },
  {
    startTime: 26.3,
    endTime: 30.6,
    text: "उंस गोड लागला म्हणून काय मुळासहीत खावे?",
  },
  {
    startTime: 30.6,
    endTime: 35.2,
    text: "प्रीतीचा पाहुणा झाला म्हणून काय फार दिवस रहावे?",
  },
  {
    startTime: 35.2,
    endTime: 39.2,
    text: "गांवचा पाटील झाला म्हणून काय गांवच बुडवावे?",
  },
  {
    startTime: 39.2,
    endTime: 45.5,
    text: "अरे कृष्णा ! अरे कान्हा ! मनरंजनमोहना",
  },
  {
    startTime: 48.5,
    endTime: 54.0,
    text: "अरे कृष्णा ! अरे कान्हा ! मनरंजनमोहना",
  },
];

export const lyricsData = [
  [
    { text: "अरे", type: "word", animation: "bounce" },
    { text: "कृष्णा", type: "word", animation: "shake" },
    { text: "!", type: "punctuation" },
    { text: "अरे", type: "word", animation: "bounce" },
    { text: "कान्हा", type: "word", animation: "shake" },
    { text: "!", type: "punctuation" },
    { text: "मनरंजनमोहना", type: "word", animation: "pulse" },
  ],
  [
    { text: "अरे", type: "word" },
    { text: "कृष्णा", type: "word" },
    { text: "!", type: "punctuation" },
    { text: "अरे", type: "word" },
    { text: "कान्हा", type: "word" },
    { text: "!", type: "punctuation" },
    { text: "मनरंजनमोहना", type: "word" },
  ],
  [
    { text: "आले", type: "word" },
    { text: "संत", type: "word" },
    { text: "घरीं", type: "word" },
    { text: "तरी", type: "word" },
    { text: "काय", type: "word" },
    { text: "बोलुन", type: "word" },
    { text: "शिणवावें", type: "word" },
    { text: "?", type: "punctuation" },
  ],
  [
    { text: "उंस", type: "word" },
    { text: "गोड", type: "word" },
    { text: "लागला", type: "word" },
    { text: "म्हणून", type: "word" },
    { text: "काय", type: "word" },
    { text: "मुळासहीत", type: "word" },
    { text: "खावे", type: "word" },
    { text: "?", type: "punctuation" },
  ],
  [
    { text: "प्रीतीचा", type: "word" },
    { text: "पाहुणा", type: "word" },
    { text: "झाला", type: "word" },
    { text: "म्हणून", type: "word" },
    { text: "काय", type: "word" },
    { text: "फार", type: "word" },
    { text: "दिवस", type: "word" },
    { text: "रहावे", type: "word" },
    { text: "?", type: "punctuation" },
  ],
  [
    { text: "गांवचा", type: "word" },
    { text: "पाटील", type: "word" },
    { text: "झाला", type: "word" },
    { text: "म्हणून", type: "word" },
    { text: "काय", type: "word" },
    { text: "गांवच", type: "word" },
    { text: "बुडवावे", type: "word" },
    { text: "?", type: "punctuation" },
  ],
  [
    { text: "अरे", type: "word" },
    { text: "कृष्णा", type: "word" },
    { text: "!", type: "punctuation" },
    { text: "अरे", type: "word" },
    { text: "कान्हा", type: "word" },
    { text: "!", type: "punctuation" },
    { text: "मनरंजनमोहना", type: "word" },
  ],
  [
    { text: "अरे", type: "word" },
    { text: "कृष्णा", type: "word" },
    { text: "!", type: "punctuation" },
    { text: "अरे", type: "word" },
    { text: "कान्हा", type: "word" },
    { text: "!", type: "punctuation" },
    { text: "मनरंजनमोहना", type: "word" },
  ],
];
